apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kafka-to-s3-vibration
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - python /bin/sh kafka2s3_simple.py
            image: iotdemo/kafka-to-s3
            imagePullPolicy: Always
            name: kafka-to-s3-vibration
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
