apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kafka-to-s3
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kafka-to-s3
            image: kafka-to-s3:latest
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: kafka-to-s3-creds
              - configMapRef:
                  name: kafka-to-s3-config
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
