apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kafka-to-s3
    app.kubernetes.io/component: kafka-to-s3
    app.kubernetes.io/instance: kafka-to-s3
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: manuela
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: "3.6"
  name: kafka-to-s3
spec:
  failedBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: kafka-to-s3:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/stefan-bergstein/simple-kafka-to-s3
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
  triggers:
  - type: ConfigChange
  successfulBuildsHistoryLimit: 3
